### ISSUE TITLE
twitter and instagram support

### ISSUE THREAD

**Issue by codestudiosupport** [jgrandja/springone2017-demo#1]
Hi, Is there any example for twitter and instagram social login? I tried to follow the minimal configuration template to setup for twitter which does not work.

**Comment by jgrandja** [comment]
@codestudiosupport Twitter does not support OAuth 2.0. Instead, it provides support for OAuth 1.0a only.

See this [reference](https://dev.twitter.com/web/sign-in/implementing)

> This page assumes that the reader knows how to sign requests using the OAuth 1.0a protocol

**NOTE:** The OAuth 2.0 Login feature in Spring Security 5.0 does not provide support for OAuth 1.0a and we do not intend to provide this support in the future given that OAuth 2.0 supersedes OAuth 1.0a.
